Change Title to RFlap
Reisande/RFLAP pull request #21
Opened 2020-01-17 23:00 UTC by pmorgan3

"React app" is too mainstream

2020-01-19 07:47 UTC, Reisande approved these changes
true

2020-02-02 04:00 UTC, bmiddha requested changes

2020-02-02 04:00 UTC, bmiddha commented on front/public/index.html
> +    <title>RFlap</title>
Shouldn't it be RFLAP?

2020-02-02 18:22 UTC, heldeo commented on front/public/index.html
> +    <title>RFlap</title>
true

2020-02-03 04:47 UTC, bmiddha approved these changes

2020-02-03 14:54 UTC, merged